export const mockPosts = [
  {
    id: 50,
    author: {
      name: '박요리',
      nickname: 'parkcooking',
      profileImage: 'https://picsum.photos/40/40?random=50',
      verified: true,
    },
    content:
      '오늘은 집에서 파스타를 만들어봤어요! 크림소스 파스타인데 정말 맛있게 나왔습니다. 요리하는 시간이 정말 힐링이에요 🍝 #요리일지 #파스타 #홈쿡',
    images: ['https://picsum.photos/500/300?random=1'],
    category: 1,
    categoryName: '요리',
    createdAt: '2024-01-15T14:30:00Z',
    likes: 67,
    retweets: 12,
    comments: 8,
    isLiked: false,
    isRetweeted: false,
    hasMoreComments: true,
    commentList: [
      {
        author: {
          name: '김맛집',
          nickname: 'kimfood',
          profileImage: 'https://picsum.photos/40/40?random=255',
          verified: false,
        },
        content: '와 정말 맛있어 보여요! 레시피 공유해주세요 😋',
        createdAt: '2024-01-15T14:45:00Z',
        likes: 5,
        isLiked: false,
      },
      {
        author: {
          name: '이홈쿡',
          nickname: 'lihomecook',
          profileImage: 'https://picsum.photos/40/40?random=254',
          verified: true,
        },
        content: '저도 파스타 좋아하는데 크림소스는 처음이에요! 도전해봐야겠어요',
        createdAt: '2024-01-15T15:00:00Z',
        likes: 3,
        isLiked: true,
      },
      {
        author: {
          name: '박요리사',
          nickname: 'parkchef',
          profileImage: 'https://picsum.photos/40/40?random=253',
          verified: false,
        },
        content: '정말 맛있어 보이네요!',
        createdAt: '2024-01-15T15:15:00Z',
        likes: 2,
        isLiked: false,
      },
    ],
  },
  {
    id: 49,
    author: {
      name: '김그림',
      nickname: 'kimdrawing',
      profileImage: 'https://picsum.photos/40/40?random=49',
      verified: false,
    },
    content:
      '오늘은 수채화로 풍경을 그려봤어요! 색감이 정말 예쁘게 나왔네요. 그림 그리는 시간이 정말 마음이 평화로워져요 ✨',
    images: [
      'https://picsum.photos/500/300?random=2',
      'https://picsum.photos/500/300?random=3',
      'https://picsum.photos/500/300?random=4',
      'https://picsum.photos/500/300?random=5',
    ],
    category: 2,
    categoryName: '그림',
    createdAt: '2024-01-15T13:15:00Z',
    likes: 89,
    retweets: 23,
    comments: 0,
    isLiked: true,
    isRetweeted: false,
    hasMoreComments: false,
    commentList: [],
  },
  {
    id: 48,
    author: {
      name: '이음악',
      nickname: 'leemusic',
      profileImage: 'https://picsum.photos/40/40?random=48',
      verified: true,
    },
    content:
      '오늘 새로운 곡을 작곡해봤어요! 피아노로 연주한 감성적인 발라드입니다 🎹 #작곡 #피아노 #발라드',
    images: ['https://picsum.photos/500/300?random=4'],
    category: 3,
    categoryName: '음악',
    createdAt: '2024-01-15T12:00:00Z',
    likes: 156,
    retweets: 45,
    comments: 1,
    isLiked: false,
    isRetweeted: true,
    hasMoreComments: false,
    commentList: [
      {
        author: {
          name: '김음악',
          nickname: 'kimmusic',
          profileImage: 'https://picsum.photos/40/40?random=253',
          verified: false,
        },
        content: '정말 감동적인 멜로디네요! 🎵',
        createdAt: '2024-01-15T12:15:00Z',
        likes: 3,
        isLiked: false,
      },
    ],
  },
  {
    id: 47,
    author: {
      name: '최영화',
      nickname: 'choimovie',
      profileImage: 'https://picsum.photos/40/40?random=47',
      verified: false,
    },
    content: '어제 본 영화가 정말 인상깊었어요. 스토리텔링이 정말 탁월했습니다! 🎬 #영화추천 #리뷰',
    images: [],
    category: 4,
    categoryName: '영화',
    createdAt: '2024-01-15T11:30:00Z',
    likes: 34,
    retweets: 8,
    comments: 0,
    isLiked: true,
    isRetweeted: false,
    hasMoreComments: false,
    commentList: [],
  },
  {
    id: 46,
    author: {
      name: '정독서',
      nickname: 'jungbook',
      profileImage: 'https://picsum.photos/40/40?random=46',
      verified: true,
    },
    content: '오늘 읽은 소설이 정말 감동적이었어요. 마지막 장면에서 눈물이... 📚 #독서 #소설 #감동',
    images: ['https://picsum.photos/500/300?random=5'],
    category: 5,
    categoryName: '독서',
    createdAt: '2024-01-15T10:45:00Z',
    likes: 78,
    retweets: 15,
    comments: 0,
    isLiked: false,
    isRetweeted: false,
    hasMoreComments: false,
    commentList: [],
  },
  {
    id: 45,
    author: {
      name: '한베이킹',
      nickname: 'hanbaking',
      profileImage: 'https://picsum.photos/40/40?random=45',
      verified: false,
    },
    content: '집에서 만든 마카롱이에요! 색깔이 정말 예쁘게 나왔어요 🧁 #베이킹 #마카롱 #디저트',
    images: [
      'https://picsum.photos/500/300?random=6',
      'https://picsum.photos/500/300?random=7',
      'https://picsum.photos/500/300?random=8',
      'https://picsum.photos/500/300?random=9',
    ],
    category: 1,
    categoryName: '요리',
    createdAt: '2024-01-15T09:30:00Z',
    likes: 92,
    retweets: 28,
    comments: 2,
    isLiked: true,
    isRetweeted: false,
    hasMoreComments: false,
    commentList: [
      {
        author: {
          name: '박디저트',
          nickname: 'parkdessert',
          profileImage: 'https://picsum.photos/40/40?random=252',
          verified: true,
        },
        content: '색깔이 정말 예쁘네요! 맛도 좋을 것 같아요 🍰',
        createdAt: '2024-01-15T09:45:00Z',
        likes: 7,
        isLiked: true,
      },
      {
        author: {
          name: '이베이킹',
          nickname: 'libaking',
          profileImage: 'https://picsum.photos/40/40?random=251',
          verified: false,
        },
        content: '레시피 공유해주세요! 저도 만들어보고 싶어요',
        createdAt: '2024-01-15T10:00:00Z',
        likes: 4,
        isLiked: false,
      },
    ],
  },
  {
    id: 44,
    author: {
      name: '윤스케치',
      nickname: 'yunsketch',
      profileImage: 'https://picsum.photos/40/40?random=44',
      verified: true,
    },
    content: '연필로 그린 인물화입니다. 디테일 표현에 신경을 많이 썼어요 ✏️ #드로잉 #인물화 #연필',
    images: ['https://picsum.photos/500/300?random=8'],
    category: 2,
    categoryName: '그림',
    createdAt: '2024-01-15T08:15:00Z',
    likes: 167,
    retweets: 52,
    comments: 15,
    isLiked: false,
    isRetweeted: true,
    hasMoreComments: true,
    commentList: [
      {
        author: {
          name: '김스케치',
          nickname: 'kimsketch',
          profileImage: 'https://picsum.photos/40/40?random=250',
          verified: false,
        },
        content: '정말 섬세하게 그리셨네요! 👏',
        createdAt: '2024-01-15T08:30:00Z',
        likes: 8,
        isLiked: true,
      },
      {
        author: {
          name: '구경꾼1',
          nickname: 'guest1',
          profileImage: 'https://picsum.photos/40/40?random=249',
          verified: false,
        },
        content: '좋은 그림 감사합니다!',
        createdAt: '2024-01-15T08:35:00Z',
        likes: 1,
        isLiked: false,
      },
      {
        author: {
          name: '서벽화',
          nickname: 'seowall',
          profileImage: 'https://picsum.photos/40/40?random=248',
          verified: false,
        },
        content: '그림이 예쁘네요!',
        createdAt: '2024-01-15T08:36:00Z',
        likes: 0,
        isLiked: false,
      },
    ],
  },
  {
    id: 43,
    author: {
      name: '장기타',
      nickname: 'jangguitar',
      profileImage: 'https://picsum.photos/40/40?random=43',
      verified: false,
    },
    content: '새로 산 기타로 연습중이에요! 손가락이 아프지만 재미있어요 🎸 #기타 #연습 #취미',
    images: ['https://picsum.photos/500/300?random=9'],
    category: 3,
    categoryName: '음악',
    createdAt: '2024-01-14T20:30:00Z',
    likes: 45,
    retweets: 7,
    comments: 0,
    isLiked: true,
    isRetweeted: false,
    hasMoreComments: false,
    commentList: [],
  },
  {
    id: 42,
    author: {
      name: '오시네마',
      nickname: 'ohcinema',
      profileImage: 'https://picsum.photos/40/40?random=42',
      verified: true,
    },
    content:
      '오늘 개봉한 영화를 보고 왔어요. 액션 시퀀스가 정말 압권이었습니다! 🎭 #영화 #액션 #개봉',
    images: [],
    category: 4,
    categoryName: '영화',
    createdAt: '2024-01-14T19:45:00Z',
    likes: 123,
    retweets: 33,
    comments: 3,
    isLiked: false,
    isRetweeted: false,
    hasMoreComments: false,
    commentList: [
      {
        author: {
          name: '이영화',
          nickname: 'leemovie',
          profileImage: 'https://picsum.photos/40/40?random=247',
          verified: true,
        },
        content: '저도 봤는데 정말 재미있었어요! 🎬',
        createdAt: '2024-01-14T20:00:00Z',
        likes: 5,
        isLiked: false,
      },
      {
        author: {
          name: '박액션',
          nickname: 'parkaction',
          profileImage: 'https://picsum.photos/40/40?random=246',
          verified: false,
        },
        content: '액션씬이 정말 멋졌어요!',
        createdAt: '2024-01-14T20:15:00Z',
        likes: 3,
        isLiked: true,
      },
      {
        author: {
          name: '김시네마',
          nickname: 'kimcinema',
          profileImage: 'https://picsum.photos/40/40?random=245',
          verified: false,
        },
        content: '저도 보고 싶네요!',
        createdAt: '2024-01-14T20:30:00Z',
        likes: 2,
        isLiked: false,
      },
    ],
  },
  {
    id: 41,
    author: {
      name: '서책방',
      nickname: 'seobookstore',
      profileImage: 'https://picsum.photos/40/40?random=41',
      verified: false,
    },
    content:
      '오늘은 카페에서 여유롭게 책을 읽었어요. 분위기가 정말 좋았습니다 ☕ #독서 #카페 #여유',
    images: ['https://picsum.photos/500/300?random=10'],
    category: 5,
    categoryName: '독서',
    createdAt: '2024-01-14T18:20:00Z',
    likes: 67,
    retweets: 12,
    comments: 4,
    isLiked: true,
    isRetweeted: false,
    hasMoreComments: true,
    commentList: [
      {
        author: {
          name: '김북카페',
          nickname: 'kimbookcafe',
          profileImage: 'https://picsum.photos/40/40?random=244',
          verified: false,
        },
        content: '어느 카페인가요? 분위기 정말 좋네요!',
        createdAt: '2024-01-14T18:30:00Z',
        likes: 2,
        isLiked: false,
      },
      {
        author: {
          name: '이독서',
          nickname: 'leereading',
          profileImage: 'https://picsum.photos/40/40?random=243',
          verified: false,
        },
        content: '저도 카페에서 책 읽는 걸 좋아해요!',
        createdAt: '2024-01-14T18:45:00Z',
        likes: 1,
        isLiked: false,
      },
      {
        author: {
          name: '박여유',
          nickname: 'parkrelax',
          profileImage: 'https://picsum.photos/40/40?random=242',
          verified: false,
        },
        content: '분위기 좋네요!',
        createdAt: '2024-01-14T19:00:00Z',
        likes: 0,
        isLiked: false,
      },
    ],
  },
  {
    id: 40,
    author: {
      name: '김쿠킹',
      nickname: 'kimcooking2',
      profileImage: 'https://picsum.photos/40/40?random=40',
      verified: false,
    },
    content: '오늘은 한식에 도전! 김치찌개를 끓여봤어요. 집밥의 맛이에요 🍲 #한식 #김치찌개 #집밥',
    images: ['https://picsum.photos/500/300?random=11'],
    category: 1,
    categoryName: '요리',
    createdAt: '2024-01-14T17:30:00Z',
    likes: 89,
    retweets: 19,
    comments: 1,
    isLiked: false,
    isRetweeted: true,
    hasMoreComments: false,
    commentList: [
      {
        author: {
          name: '김치찌개땜에사는사람',
          nickname: 'kimchijjige',
          profileImage: 'https://picsum.photos/40/40?random=243',
          verified: false,
        },
        content: '와 김치찌개 정말 맛있어 보여요! 레시피 알려주세요.',
        createdAt: '2024-01-14T17:45:00Z',
        likes: 3,
        isLiked: false,
      },
    ],
  },
  {
    id: 39,
    author: {
      name: '박아트',
      nickname: 'parkart',
      profileImage: 'https://picsum.photos/40/40?random=39',
      verified: true,
    },
    content: '유화로 그린 풍경화입니다. 붓 터치가 마음에 들어요 🎨 #유화 #풍경화 #아트',
    images: [
      'https://picsum.photos/500/300?random=12',
      'https://picsum.photos/500/300?random=13',
      'https://picsum.photos/500/300?random=14',
      'https://picsum.photos/500/300?random=15',
    ],
    category: 2,
    categoryName: '그림',
    createdAt: '2024-01-14T16:15:00Z',
    likes: 234,
    retweets: 67,
    comments: 3,
    isLiked: true,
    isRetweeted: false,
    hasMoreComments: false,
    commentList: [
      {
        author: {
          name: '최아티스트',
          nickname: 'choiartist',
          profileImage: 'https://picsum.photos/40/40?random=241',
          verified: true,
        },
        content: '색감이 정말 아름다워요! 어떤 브랜드 물감을 사용하셨나요?',
        createdAt: '2024-01-14T16:30:00Z',
        likes: 12,
        isLiked: false,
      },
      {
        author: {
          name: '김화가',
          nickname: 'kimpainter',
          profileImage: 'https://picsum.photos/40/40?random=242',
          verified: false,
        },
        content: '풍경의 분위기가 정말 잘 표현되었네요! 👏',
        createdAt: '2024-01-14T16:45:00Z',
        likes: 8,
        isLiked: true,
      },
      {
        author: {
          name: '박드로잉',
          nickname: 'parkdrawing',
          profileImage: 'https://picsum.photos/40/40?random=241',
          verified: false,
        },
        content: '저도 이런 스타일로 그려보고 싶어요. 팁이 있으시면 알려주세요!',
        createdAt: '2024-01-14T17:00:00Z',
        likes: 5,
        isLiked: false,
      },
    ],
  },
  {
    id: 38,
    author: {
      name: '조바이올린',
      nickname: 'joviolin',
      profileImage: 'https://picsum.photos/40/40?random=38',
      verified: false,
    },
    content: '바이올린 연습 중이에요! 아직 서툴지만 조금씩 늘고 있어요 🎻 #바이올린 #연습 #클래식',
    images: [],
    category: 3,
    categoryName: '음악',
    createdAt: '2024-01-14T15:45:00Z',
    likes: 56,
    retweets: 11,
    comments: 0,
    isLiked: false,
    isRetweeted: false,
    hasMoreComments: false,
    commentList: [],
  },
  {
    id: 37,
    author: {
      name: '이필름',
      nickname: 'leefilm',
      profileImage: 'https://picsum.photos/40/40?random=37',
      verified: true,
    },
    content:
      '단편 영화를 제작하고 있어요! 스토리보드 작업이 정말 재미있어요 🎬 #영화제작 #단편영화 #창작',
    images: ['https://picsum.photos/500/300?random=14'],
    category: 4,
    categoryName: '영화',
    createdAt: '2024-01-14T14:30:00Z',
    likes: 145,
    retweets: 42,
    comments: 0,
    isLiked: true,
    isRetweeted: true,
    hasMoreComments: false,
    commentList: [],
  },
  {
    id: 36,
    author: {
      name: '최라이터',
      nickname: 'choiwriter',
      profileImage: 'https://picsum.photos/40/40?random=36',
      verified: false,
    },
    content: '새로운 시집을 읽고 있어요. 언어의 아름다움에 감탄하고 있습니다 📖 #시 #문학 #언어',
    images: [],
    category: 5,
    categoryName: '독서',
    createdAt: '2024-01-14T13:20:00Z',
    likes: 73,
    retweets: 18,
    comments: 5,
    isLiked: false,
    isRetweeted: false,
    hasMoreComments: true,
    commentList: [
      {
        author: {
          name: '김독자',
          nickname: 'kimreader',
          profileImage: 'https://picsum.photos/40/40?random=240',
          verified: false,
        },
        content: '좋은 시집인가요? 추천해주세요!',
        createdAt: '2024-01-14T13:30:00Z',
        likes: 2,
        isLiked: false,
      },
      {
        author: {
          name: '시집소녀',
          nickname: 'girlreader',
          profileImage: 'https://picsum.photos/40/40?random=239',
          verified: false,
        },
        content: '시집을 읽는 것이 즐거워요.',
        createdAt: '2024-01-14T13:30:00Z',
        likes: 2,
        isLiked: false,
      },
      {
        author: {
          name: '수필의대가',
          nickname: 'kingofwriting',
          profileImage: 'https://picsum.photos/40/40?random=238',
          verified: false,
        },
        content: '언어의 아름다움을 느낍니다.',
        createdAt: '2024-01-14T13:30:00Z',
        likes: 2,
        isLiked: false,
      },
    ],
  },
  {
    id: 35,
    author: {
      name: '정파티시에',
      nickname: 'jungpatissier',
      profileImage: 'https://picsum.photos/40/40?random=35',
      verified: true,
    },
    content: '오늘은 크로와상에 도전했어요! 겉바속촉의 완벽한 식감 🥐 #베이킹 #크로와상 #파티시에',
    images: [
      'https://picsum.photos/500/300?random=16',
      'https://picsum.photos/500/300?random=17',
      'https://picsum.photos/500/300?random=18',
    ],
    category: 1,
    categoryName: '요리',
    createdAt: '2024-01-14T12:10:00Z',
    likes: 198,
    retweets: 56,
    comments: 1,
    isLiked: true,
    isRetweeted: false,
    hasMoreComments: false,
    commentList: [
      {
        author: {
          name: '김문학',
          nickname: 'kimliterature',
          profileImage: 'https://picsum.photos/40/40?random=237',
          verified: false,
        },
        content: '어떤 고전 소설인가요? 저도 다시 읽어보고 싶네요.',
        createdAt: '2024-01-12T19:45:00Z',
        likes: 3,
        isLiked: false,
      },
    ],
  },
  {
    id: 34,
    author: {
      name: '강디자인',
      nickname: 'kangdesign',
      profileImage: 'https://picsum.photos/40/40?random=34',
      verified: false,
    },
    content: '포스터 디자인 작업 중이에요. 컬러 조합이 마음에 들어요 🎨 #디자인 #포스터 #그래픽',
    images: ['https://picsum.photos/500/300?random=17'],
    category: 2,
    categoryName: '그림',
    createdAt: '2024-01-14T11:30:00Z',
    likes: 112,
    retweets: 29,
    comments: 0,
    isLiked: false,
    isRetweeted: true,
    hasMoreComments: false,
    commentList: [],
  },
  {
    id: 33,
    author: {
      name: '유드럼',
      nickname: 'yudrum',
      profileImage: 'https://picsum.photos/40/40?random=33',
      verified: true,
    },
    content:
      '새로운 드럼 패턴을 연습하고 있어요! 리듬감이 점점 좋아지는 것 같아요 🥁 #드럼 #리듬 #연주',
    images: [],
    category: 3,
    categoryName: '음악',
    createdAt: '2024-01-14T10:45:00Z',
    likes: 87,
    retweets: 22,
    comments: 9,
    isLiked: true,
    isRetweeted: false,
    hasMoreComments: true,
    commentList: [
      {
        author: {
          name: '박드럼',
          nickname: 'parkdrum',
          profileImage: 'https://picsum.photos/40/40?random=236',
          verified: true,
        },
        content: '새로운 패턴 기대됩니다! 🥁',
        createdAt: '2024-01-14T11:01:00Z',
        likes: 4,
        isLiked: false,
      },
      {
        author: {
          name: '생활속의드럼',
          nickname: 'lifedrum',
          profileImage: 'https://picsum.photos/40/40?random=235',
          verified: true,
        },
        content: '굳굳',
        createdAt: '2024-01-14T11:02:00Z',
        likes: 0,
        isLiked: false,
      },
      {
        author: {
          name: '연습생드럼',
          nickname: 'studentdrum',
          profileImage: 'https://picsum.photos/40/40?random=234',
          verified: true,
        },
        content: '저도 기대됩니다!',
        createdAt: '2024-01-14T11:03:00Z',
        likes: 0,
        isLiked: false,
      },
    ],
  },
  {
    id: 32,
    author: {
      name: '신감독',
      nickname: 'shindirector',
      profileImage: 'https://picsum.photos/40/40?random=32',
      verified: false,
    },
    content:
      '영화 촬영 현장의 모습이에요. 배우들의 연기가 정말 인상적이었어요 🎥 #촬영 #영화 #현장',
    images: [
      'https://picsum.photos/500/300?random=19',
      'https://picsum.photos/500/300?random=20',
      'https://picsum.photos/500/300?random=21',
      'https://picsum.photos/500/300?random=22',
    ],
    category: 4,
    categoryName: '영화',
    createdAt: '2024-01-14T09:20:00Z',
    likes: 156,
    retweets: 44,
    comments: 0,
    isLiked: false,
    isRetweeted: false,
    hasMoreComments: false,
    commentList: [],
  },
  {
    id: 31,
    author: {
      name: '민북클럽',
      nickname: 'minbookclub',
      profileImage: 'https://picsum.photos/40/40?random=31',
      verified: true,
    },
    content:
      '이번 달 독서 모임에서 읽을 책이에요. 주제가 정말 흥미로워요 📚 #독서모임 #책추천 #토론',
    images: ['https://picsum.photos/500/300?random=20'],
    category: 5,
    categoryName: '독서',
    createdAt: '2024-01-14T08:15:00Z',
    likes: 94,
    retweets: 25,
    comments: 8,
    isLiked: true,
    isRetweeted: true,
    hasMoreComments: true,
    commentList: [
      {
        author: {
          name: '김독서',
          nickname: 'kimreading',
          profileImage: 'https://picsum.photos/40/40?random=233',
          verified: false,
        },
        content: '저도 이 책 읽어봤는데 정말 좋았어요!',
        createdAt: '2024-01-14T08:30:00Z',
        likes: 4,
        isLiked: false,
      },
      {
        author: {
          name: '선우독서',
          nickname: 'seonyureading',
          profileImage: 'https://picsum.photos/40/40?random=232',
          verified: true,
        },
        content: '한번 읽어보고 싶네요!',
        createdAt: '2024-01-14T08:30:00Z',
        likes: 4,
        isLiked: false,
      },
    ],
  },
  {
    id: 30,
    author: {
      name: '황셰프',
      nickname: 'hwangchef',
      profileImage: 'https://picsum.photos/40/40?random=30',
      verified: false,
    },
    content:
      '오늘의 특별 메뉴! 새우 리조또입니다. 크림의 부드러움이 일품이에요 🦐 #리조또 #새우 #이탈리안',
    images: ['https://picsum.photos/500/300?random=21'],
    category: 1,
    categoryName: '요리',
    createdAt: '2024-01-13T20:30:00Z',
    likes: 167,
    retweets: 48,
    comments: 0,
    isLiked: false,
    isRetweeted: false,
    hasMoreComments: false,
    commentList: [],
  },
  {
    id: 29,
    author: {
      name: '구일러스트',
      nickname: 'guillustrator',
      profileImage: 'https://picsum.photos/40/40?random=29',
      verified: true,
    },
    content: '캐릭터 일러스트 작업 완료! 표정 디테일에 공들였어요 ✨ #일러스트 #캐릭터 #디지털아트',
    images: [
      'https://picsum.photos/500/300?random=23',
      'https://picsum.photos/500/300?random=24',
      'https://picsum.photos/500/300?random=25',
    ],
    category: 2,
    categoryName: '그림',
    createdAt: '2024-01-13T19:45:00Z',
    likes: 289,
    retweets: 78,
    comments: 0,
    isLiked: true,
    isRetweeted: false,
    hasMoreComments: false,
    commentList: [],
  },
  {
    id: 28,
    author: {
      name: '여행속의일러스트',
      nickname: 'travelillustrator',
      profileImage: 'https://picsum.photos/40/40?random=28',
      verified: false,
    },
    content: '일러스트 작업 완료! 표정 디테일에 공들였어요 ✨ #일러스트 #캐릭터 #디지털아트',
    images: [
      'https://picsum.photos/500/300?random=23',
      'https://picsum.photos/500/300?random=24',
      'https://picsum.photos/500/300?random=25',
    ],
    category: 2,
    categoryName: '그림',
    createdAt: '2024-01-13T19:44:00Z',
    likes: 289,
    retweets: 78,
    comments: 0,
    isLiked: true,
    isRetweeted: false,
    hasMoreComments: false,
    commentList: [],
  },
  {
    id: 27,
    author: {
      name: '임작곡',
      nickname: 'limcomposer',
      profileImage: 'https://picsum.photos/40/40?random=27',
      verified: false,
    },
    content: '새로운 재즈 곡을 작곡했어요! 색소폰 솔로 부분이 마음에 들어요 🎷 #재즈 #작곡 #색소폰',
    images: [],
    category: 3,
    categoryName: '음악',
    createdAt: '2024-01-13T18:20:00Z',
    likes: 134,
    retweets: 36,
    comments: 0,
    isLiked: false,
    isRetweeted: true,
    hasMoreComments: false,
    commentList: [],
  },
  {
    id: 26,
    author: {
      name: '류에세이',
      nickname: 'ryuessay',
      profileImage: 'https://picsum.photos/40/40?random=26',
      verified: false,
    },
    content:
      '오늘 읽은 에세이집이 마음에 와 닿았어요. 일상의 소중함을 다시 생각하게 됐습니다 💭 #에세이 #일상 #감상',
    images: [],
    category: 5,
    categoryName: '독서',
    createdAt: '2024-01-13T16:30:00Z',
    likes: 76,
    retweets: 19,
    comments: 0,
    isLiked: false,
    isRetweeted: false,
    hasMoreComments: false,
    commentList: [],
  },
  {
    id: 25,
    author: {
      name: '백홈메이드',
      nickname: 'baekhomemade',
      profileImage: 'https://picsum.photos/40/40?random=25',
      verified: true,
    },
    content: '수제 빵을 만들었어요! 발효부터 굽기까지 정성스럽게 🍞 #수제빵 #홈베이킹 #발효',
    images: [
      'https://picsum.photos/500/300?random=26',
      'https://picsum.photos/500/300?random=27',
      'https://picsum.photos/500/300?random=28',
      'https://picsum.photos/500/300?random=29',
    ],
    category: 1,
    categoryName: '요리',
    createdAt: '2024-01-13T15:45:00Z',
    likes: 145,
    retweets: 41,
    comments: 0,
    isLiked: true,
    isRetweeted: true,
    hasMoreComments: false,
    commentList: [],
  },
  {
    id: 24,
    author: {
      name: '문캘리그라피',
      nickname: 'muncalligraphy',
      profileImage: 'https://picsum.photos/40/40?random=24',
      verified: false,
    },
    content: '캘리그라피 작품을 완성했어요! 붓의 느낌이 살아있는 글씨 ✍️ #캘리그라피 #붓글씨 #서예',
    images: ['https://picsum.photos/500/300?random=27'],
    category: 2,
    categoryName: '그림',
    createdAt: '2024-01-13T14:20:00Z',
    likes: 187,
    retweets: 53,
    comments: 12,
    isLiked: false,
    isRetweeted: false,
    hasMoreComments: true,
    commentList: [
      {
        author: {
          name: '조명필',
          nickname: 'joomcinephile',
          profileImage: 'https://picsum.photos/40/40?random=300',
          verified: false,
        },
        content: '좋은 느낌이 들어요!',
        createdAt: '2024-01-13T14:30:00Z',
        likes: 1,
        isLiked: false,
      },
      {
        author: {
          name: '김디자인',
          nickname: 'kimdesign',
          profileImage: 'https://picsum.photos/40/40?random=301',
          verified: false,
        },
        content: '디자인이 정말 멋져요! 컬러 조합이 인상적이네요.',
        createdAt: '2024-01-13T14:31:00Z',
        likes: 1,
        isLiked: false,
      },
      {
        author: {
          name: '이그래픽',
          nickname: 'leegraphic',
          profileImage: 'https://picsum.photos/40/40?random=302',
          verified: false,
        },
        content: '포스터 디자인 팁이 있으시면 알려주세요!',
        createdAt: '2024-01-13T14:32:00Z',
        likes: 1,
        isLiked: false,
      },
    ],
  },
  {
    id: 23,
    author: {
      name: '송보컬',
      nickname: 'songvocal',
      profileImage: 'https://picsum.photos/40/40?random=23',
      verified: true,
    },
    content: '새로운 노래를 녹음했어요! 감정을 담아 불렀습니다 🎤 #보컬 #녹음 #감정',
    images: [],
    category: 3,
    categoryName: '음악',
    createdAt: '2024-01-13T13:30:00Z',
    likes: 223,
    retweets: 64,
    comments: 0,
    isLiked: true,
    isRetweeted: false,
    hasMoreComments: false,
    commentList: [],
  },
  {
    id: 22,
    author: {
      name: '안평론가',
      nickname: 'ancritic',
      profileImage: 'https://picsum.photos/40/40?random=22',
      verified: false,
    },
    content:
      '이번 주 개봉 영화들을 분석해봤어요. 각각의 특색이 뚜렷하네요 🎭 #영화평론 #분석 #개봉작',
    images: ['https://picsum.photos/500/300?random=28'],
    category: 4,
    categoryName: '영화',
    createdAt: '2024-01-13T12:15:00Z',
    likes: 109,
    retweets: 31,
    comments: 14,
    isLiked: false,
    isRetweeted: true,
    hasMoreComments: true,
    commentList: [
      {
        author: {
          name: '김시네필',
          nickname: 'kimcinephile',
          profileImage: 'https://picsum.photos/40/40?random=230',
          verified: false,
        },
        content: '어떤 영화들이 제일 인상 깊으셨나요?',
        createdAt: '2024-01-13T12:30:00Z',
        likes: 6,
        isLiked: false,
      },
      {
        author: {
          name: '이리뷰어',
          nickname: 'leereviewer',
          profileImage: 'https://picsum.photos/40/40?random=229',
          verified: true,
        },
        content: '저도 이 평론가분 리뷰 자주 봐요!',
        createdAt: '2024-01-13T12:45:00Z',
        likes: 3,
        isLiked: true,
      },
      {
        author: {
          name: '박영화',
          nickname: 'parkmovie',
          profileImage: 'https://picsum.photos/40/40?random=228',
          verified: false,
        },
        content: '분석 감사합니다!',
        createdAt: '2024-01-13T13:00:00Z',
        likes: 2,
        isLiked: false,
      },
    ],
  },
  {
    id: 21,
    author: {
      name: '홍도서관',
      nickname: 'honglibrary',
      profileImage: 'https://picsum.photos/40/40?random=21',
      verified: true,
    },
    content:
      '조용한 도서관에서 집중해서 책을 읽었어요. 이런 시간이 정말 소중해요 📖 #도서관 #집중 #독서시간',
    images: ['https://picsum.photos/500/300?random=29'],
    category: 5,
    categoryName: '독서',
    createdAt: '2024-01-13T11:30:00Z',
    likes: 82,
    retweets: 16,
    comments: 7,
    isLiked: true,
    isRetweeted: false,
    hasMoreComments: true,
    commentList: [
      {
        author: {
          name: '최북컬렉터',
          nickname: 'choibookcollector',
          profileImage: 'https://picsum.photos/40/40?random=227',
          verified: true,
        },
        content: '어떤 책들이 소중하게 느껴지시나요? 궁금해요!',
        createdAt: '2024-01-13T11:45:00Z',
        likes: 5,
        isLiked: false,
      },
      {
        author: {
          name: '김도서',
          nickname: 'kimbook',
          profileImage: 'https://picsum.photos/40/40?random=226',
          verified: false,
        },
        content: '도서관 분위기 좋아요!',
        createdAt: '2024-01-13T12:00:00Z',
        likes: 3,
        isLiked: false,
      },
      {
        author: {
          name: '이집중',
          nickname: 'leeconcentration',
          profileImage: 'https://picsum.photos/40/40?random=225',
          verified: false,
        },
        content: '저도 도서관에서 집중 잘돼요!',
        createdAt: '2024-01-13T12:15:00Z',
        likes: 2,
        isLiked: false,
      },
    ],
  },
  {
    id: 20,
    author: {
      name: '변퓨전',
      nickname: 'byeonfusion',
      profileImage: 'https://picsum.photos/40/40?random=20',
      verified: false,
    },
    content: '퓨전 요리에 도전! 한식과 양식의 만남이에요 🍽️ #퓨전요리 #한양식 #창작요리',
    images: [
      'https://picsum.photos/500/300?random=30',
      'https://picsum.photos/500/300?random=31',
      'https://picsum.photos/500/300?random=32',
    ],
    category: 1,
    categoryName: '요리',
    createdAt: '2024-01-13T10:45:00Z',
    likes: 156,
    retweets: 43,
    comments: 0,
    isLiked: false,
    isRetweeted: false,
    hasMoreComments: false,
    commentList: [],
  },
  {
    id: 19,
    author: {
      name: '표조각',
      nickname: 'pyosculpture',
      profileImage: 'https://picsum.photos/40/40?random=19',
      verified: true,
    },
    content:
      '점토로 만든 조각 작품이에요! 손으로 직접 빚는 재미가 있어요 🏺 #조각 #점토 #핸드메이드',
    images: ['https://picsum.photos/500/300?random=32'],
    category: 2,
    categoryName: '그림',
    createdAt: '2024-01-13T09:20:00Z',
    likes: 134,
    retweets: 38,
    comments: 0,
    isLiked: true,
    isRetweeted: true,
    hasMoreComments: false,
    commentList: [],
  },
  {
    id: 18,
    author: {
      name: '곽밴드',
      nickname: 'gwakband',
      profileImage: 'https://picsum.photos/40/40?random=18',
      verified: false,
    },
    content: '밴드 연습이 끝났어요! 새로운 곡의 편곡이 완성되었습니다 🎸 #밴드 #연습 #편곡',
    images: [],
    category: 3,
    categoryName: '음악',
    createdAt: '2024-01-13T08:30:00Z',
    likes: 98,
    retweets: 24,
    comments: 0,
    isLiked: false,
    isRetweeted: false,
    hasMoreComments: false,
    commentList: [],
  },
  {
    id: 17,
    author: {
      name: '허시나리오',
      nickname: 'heoscenario',
      profileImage: 'https://picsum.photos/40/40?random=17',
      verified: true,
    },
    content:
      '새로운 시나리오를 쓰고 있어요. 캐릭터들의 대사가 살아나는 느낌이에요 ✍️ #시나리오 #창작 #대사',
    images: ['https://picsum.photos/500/300?random=33'],
    category: 4,
    categoryName: '영화',
    createdAt: '2024-01-12T20:15:00Z',
    likes: 167,
    retweets: 49,
    comments: 0,
    isLiked: true,
    isRetweeted: false,
    hasMoreComments: false,
    commentList: [],
  },
  {
    id: 16,
    author: {
      name: '고소설',
      nickname: 'gonovel',
      profileImage: 'https://picsum.photos/40/40?random=16',
      verified: false,
    },
    content:
      '고전 소설을 다시 읽고 있어요. 시대를 초월한 메시지가 인상적이에요 📚 #고전소설 #문학 #시대초월',
    images: [],
    category: 5,
    categoryName: '독서',
    createdAt: '2024-01-12T19:30:00Z',
    likes: 89,
    retweets: 21,
    comments: 8,
    isLiked: false,
    isRetweeted: true,
    hasMoreComments: true,
    commentList: [
      {
        author: {
          name: '고전문학박사',
          nickname: 'classicliterature',
          profileImage: 'https://picsum.photos/40/40?random=224',
          verified: false,
        },
        content: '고전문학은 정말 좋아요.',
        createdAt: '2024-01-12T19:45:00Z',
        likes: 3,
        isLiked: false,
      },
      {
        author: {
          name: '이소설',
          nickname: 'leenovel',
          profileImage: 'https://picsum.photos/40/40?random=223',
          verified: false,
        },
        content: '고전 소설의 깊이가 정말 대단하죠!',
        createdAt: '2024-01-12T20:00:00Z',
        likes: 2,
        isLiked: false,
      },
      {
        author: {
          name: '박문학',
          nickname: 'parkliterature',
          profileImage: 'https://picsum.photos/40/40?random=222',
          verified: false,
        },
        content: '추천 감사합니다!',
        createdAt: '2024-01-12T20:15:00Z',
        likes: 1,
        isLiked: false,
      },
    ],
  },
  {
    id: 15,
    author: {
      name: '강스시',
      nickname: 'kangsushi',
      profileImage: 'https://picsum.photos/40/40?random=15',
      verified: true,
    },
    content: '집에서 스시를 만들어봤어요! 생각보다 어렵지만 재미있어요 🍣 #스시 #일식 #홈메이드',
    images: [
      'https://picsum.photos/500/300?random=34',
      'https://picsum.photos/500/300?random=35',
      'https://picsum.photos/500/300?random=36',
      'https://picsum.photos/500/300?random=37',
    ],
    category: 1,
    categoryName: '요리',
    createdAt: '2024-01-12T18:45:00Z',
    likes: 234,
    retweets: 67,
    comments: 0,
    isLiked: true,
    isRetweeted: false,
    hasMoreComments: false,
    commentList: [],
  },
  {
    id: 14,
    author: {
      name: '나만화',
      nickname: 'namanhwa',
      profileImage: 'https://picsum.photos/40/40?random=14',
      verified: false,
    },
    content:
      '웹툰 스토리보드를 그리고 있어요! 캐릭터들의 감정 표현이 중요해요 💭 #웹툰 #스토리보드 #만화',
    images: ['https://picsum.photos/500/300?random=36'],
    category: 2,
    categoryName: '그림',
    createdAt: '2024-01-12T17:20:00Z',
    likes: 178,
    retweets: 52,
    comments: 0,
    isLiked: false,
    isRetweeted: false,
    hasMoreComments: false,
    commentList: [],
  },
  {
    id: 13,
    author: {
      name: '도재즈',
      nickname: 'dojazz',
      profileImage: 'https://picsum.photos/40/40?random=13',
      verified: true,
    },
    content: '재즈 클럽에서 연주했어요! 즉흥 연주의 매력에 빠져있어요 🎺 #재즈 #즉흥연주 #클럽',
    images: [],
    category: 3,
    categoryName: '음악',
    createdAt: '2024-01-12T16:30:00Z',
    likes: 145,
    retweets: 41,
    comments: 23,
    isLiked: true,
    isRetweeted: true,
    hasMoreComments: true,
    commentList: [
      {
        author: {
          name: '김재즈',
          nickname: 'kimjazz',
          profileImage: 'https://picsum.photos/40/40?random=221',
          verified: false,
        },
        content: '어떤 재즈 음악이었나요? 궁금하네요!',
        createdAt: '2024-01-12T18:15:00Z',
        likes: 10,
        isLiked: false,
      },
      {
        author: {
          name: '이라이브',
          nickname: 'leelive',
          profileImage: 'https://picsum.photos/40/40?random=220',
          verified: true,
        },
        content: '저도 재즈 공연 좋아해요! 👍',
        createdAt: '2024-01-12T18:30:00Z',
        likes: 7,
        isLiked: true,
      },
      {
        author: {
          name: '박즉흥',
          nickname: 'parkimprov',
          profileImage: 'https://picsum.photos/40/40?random=219',
          verified: false,
        },
        content: '즉흥 연주 정말 멋져요!',
        createdAt: '2024-01-12T18:45:00Z',
        likes: 5,
        isLiked: false,
      },
    ],
  },
  {
    id: 12,
    author: {
      name: '길거리영화',
      nickname: 'streetmovie',
      profileImage: 'https://picsum.photos/40/40?random=12',
      verified: false,
    },
    content: '새로운 구상을 만들고 있어요! 영화 제작에 많은 시간이 걸렸어요 🎬 #영화 #제작 #길거리',
    images: ['https://picsum.photos/500/300?random=39'],
    category: 4,
    categoryName: '영화',
    createdAt: '2024-01-12T15:25:00Z',
    likes: 123,
    retweets: 35,
    comments: 0,
    isLiked: false,
    isRetweeted: false,
    hasMoreComments: false,
    commentList: [],
  },
  {
    id: 11,
    author: {
      name: '라다큐',
      nickname: 'radocu',
      profileImage: 'https://picsum.photos/40/40?random=11',
      verified: false,
    },
    content:
      '다큐멘터리 편집 작업이 마무리되었어요! 스토리텔링에 많은 신경을 썼습니다 🎬 #다큐멘터리 #편집 #스토리텔링',
    images: [
      'https://picsum.photos/500/300?random=38',
      'https://picsum.photos/500/300?random=39',
      'https://picsum.photos/500/300?random=40',
    ],
    category: 4,
    categoryName: '영화',
    createdAt: '2024-01-12T15:15:00Z',
    likes: 123,
    retweets: 35,
    comments: 15,
    isLiked: false,
    isRetweeted: false,
    hasMoreComments: true,
    commentList: [
      {
        author: {
          name: '박다큐',
          nickname: 'parkdocu',
          profileImage: 'https://picsum.photos/40/40?random=215',
          verified: false,
        },
        content: '어떤 다큐멘터리인가요? 기대됩니다!',
        createdAt: '2024-01-12T15:30:00Z',
        likes: 7,
        isLiked: false,
      },
      {
        author: {
          name: '김편집',
          nickname: 'kimedit',
          profileImage: 'https://picsum.photos/40/40?random=214',
          verified: false,
        },
        content: '스토리텔링이 정말 중요하죠!',
        createdAt: '2024-01-12T15:45:00Z',
        likes: 5,
        isLiked: false,
      },
      {
        author: {
          name: '이다큐',
          nickname: 'leedocu',
          profileImage: 'https://picsum.photos/40/40?random=213',
          verified: false,
        },
        content: '작품 기대됩니다!',
        createdAt: '2024-01-12T16:00:00Z',
        likes: 3,
        isLiked: false,
      },
    ],
  },
  {
    id: 10,
    author: {
      name: '바디저트',
      nickname: 'badessert',
      profileImage: 'https://picsum.photos/40/40?random=10',
      verified: false,
    },
    content:
      '티라미수를 만들어봤어요! 마스카포네 치즈의 부드러움이 일품이에요 🍰 #티라미수 #디저트 #마스카포네',
    images: ['https://picsum.photos/500/300?random=39'],
    category: 1,
    categoryName: '요리',
    createdAt: '2024-01-12T13:45:00Z',
    likes: 198,
    retweets: 56,
    comments: 0,
    isLiked: false,
    isRetweeted: true,
    hasMoreComments: false,
    commentList: [],
  },
  {
    id: 9,
    author: {
      name: '사픽셀',
      nickname: 'sapixel',
      profileImage: 'https://picsum.photos/40/40?random=9',
      verified: true,
    },
    content:
      '픽셀 아트 작업을 하고 있어요! 작은 도트 하나하나가 모여 그림이 되는 게 신기해요 🎮 #픽셀아트 #도트 #게임아트',
    images: [
      'https://picsum.photos/500/300?random=41',
      'https://picsum.photos/500/300?random=42',
      'https://picsum.photos/500/300?random=43',
      'https://picsum.photos/500/300?random=44',
    ],
    category: 2,
    categoryName: '그림',
    createdAt: '2024-01-12T12:20:00Z',
    likes: 267,
    retweets: 73,
    comments: 0,
    isLiked: true,
    isRetweeted: false,
    hasMoreComments: false,
    commentList: [],
  },
  {
    id: 8,
    author: {
      name: '아일렉트로',
      nickname: 'aelectro',
      profileImage: 'https://picsum.photos/40/40?random=8',
      verified: false,
    },
    content:
      '일렉트로닉 음악을 제작하고 있어요! 신디사이저의 소리가 매력적이에요 🎹 #일렉트로닉 #신디사이저 #제작',
    images: [],
    category: 3,
    categoryName: '음악',
    createdAt: '2024-01-12T11:30:00Z',
    likes: 134,
    retweets: 39,
    comments: 17,
    isLiked: false,
    isRetweeted: false,
    hasMoreComments: true,
    commentList: [
      {
        author: {
          name: '박일렉',
          nickname: 'parkelectro',
          profileImage: 'https://picsum.photos/40/40?random=212',
          verified: false,
        },
        content: '새로운 곡 기대됩니다! 🎶',
        createdAt: '2024-01-12T11:45:00Z',
        likes: 8,
        isLiked: false,
      },
      {
        author: {
          name: '이신디',
          nickname: 'leesynth',
          profileImage: 'https://picsum.photos/40/40?random=211',
          verified: true,
        },
        content: '신디사이저 소리 정말 좋아요!',
        createdAt: '2024-01-12T12:00:00Z',
        likes: 5,
        isLiked: true,
      },
      {
        author: {
          name: '김제작',
          nickname: 'kimproduction',
          profileImage: 'https://picsum.photos/40/40?random=210',
          verified: false,
        },
        content: '일렉트로닉 음악 멋져요!',
        createdAt: '2024-01-12T12:15:00Z',
        likes: 3,
        isLiked: false,
      },
    ],
  },
  {
    id: 7,
    author: {
      name: '자애니메이션',
      nickname: 'jaanimation',
      profileImage: 'https://picsum.photos/40/40?random=7',
      verified: true,
    },
    content:
      '단편 애니메이션을 제작하고 있어요! 캐릭터들이 움직이는 모습이 생생해요 🎨 #애니메이션 #단편 #캐릭터',
    images: ['https://picsum.photos/500/300?random=42'],
    category: 4,
    categoryName: '영화',
    createdAt: '2024-01-12T10:45:00Z',
    likes: 189,
    retweets: 54,
    comments: 0,
    isLiked: true,
    isRetweeted: true,
    hasMoreComments: false,
    commentList: [],
  },
  {
    id: 6,
    author: {
      name: '차역사',
      nickname: 'chahistory',
      profileImage: 'https://picsum.photos/40/40?random=6',
      verified: false,
    },
    content:
      '역사서를 읽으며 과거를 여행하고 있어요. 교훈이 되는 이야기들이 많아요 📜 #역사 #과거 #교훈',
    images: [],
    category: 5,
    categoryName: '독서',
    createdAt: '2024-01-12T09:20:00Z',
    likes: 98,
    retweets: 28,
    comments: 9,
    isLiked: false,
    isRetweeted: false,
    hasMoreComments: true,
    commentList: [
      {
        author: {
          name: '김역사',
          nickname: 'kimhistory',
          profileImage: 'https://picsum.photos/40/40?random=209',
          verified: false,
        },
        content: '어떤 역사서인가요? 궁금하네요!',
        createdAt: '2024-01-12T09:35:00Z',
        likes: 4,
        isLiked: false,
      },
      {
        author: {
          name: '이과거',
          nickname: 'leepast',
          profileImage: 'https://picsum.photos/40/40?random=208',
          verified: false,
        },
        content: '역사에서 배울 점이 많죠!',
        createdAt: '2024-01-12T09:50:00Z',
        likes: 2,
        isLiked: false,
      },
      {
        author: {
          name: '박교훈',
          nickname: 'parklesson',
          profileImage: 'https://picsum.photos/40/40?random=207',
          verified: false,
        },
        content: '교훈이 되는 이야기 좋아요!',
        createdAt: '2024-01-12T10:05:00Z',
        likes: 1,
        isLiked: false,
      },
    ],
  },
  {
    id: 5,
    author: {
      name: '카브런치',
      nickname: 'kabrunch',
      profileImage: 'https://picsum.photos/40/40?random=5',
      verified: true,
    },
    content:
      '주말 브런치 메뉴를 준비했어요! 팬케이크와 과일의 조화가 완벽해요 🥞 #브런치 #팬케이크 #주말',
    images: [
      'https://picsum.photos/500/300?random=45',
      'https://picsum.photos/500/300?random=46',
      'https://picsum.photos/500/300?random=47',
      'https://picsum.photos/500/300?random=48',
    ],
    category: 1,
    categoryName: '요리',
    createdAt: '2024-01-12T08:30:00Z',
    likes: 223,
    retweets: 61,
    comments: 0,
    isLiked: true,
    isRetweeted: false,
    hasMoreComments: false,
    commentList: [],
  },
  {
    id: 4,
    author: {
      name: '타스케치북',
      nickname: 'tasketchbook',
      profileImage: 'https://picsum.photos/40/40?random=4',
      verified: false,
    },
    content:
      '스케치북에 자연을 그리고 있어요. 나무와 꽃들의 디테일을 담아보려고 해요 🌸 #스케치 #자연 #디테일',
    images: ['https://picsum.photos/500/300?random=45'],
    category: 2,
    categoryName: '그림',
    createdAt: '2024-01-11T20:15:00Z',
    likes: 156,
    retweets: 44,
    comments: 20,
    isLiked: false,
    isRetweeted: true,
    hasMoreComments: true,
    commentList: [
      {
        author: {
          name: '지하철속화가',
          nickname: 'subwayartist',
          profileImage: 'https://picsum.photos/40/40?random=206',
          verified: false,
        },
        content: '나무 묘사가 정말 디테일하네요! 🌳',
        createdAt: '2024-01-11T20:30:00Z',
        likes: 9,
        isLiked: false,
      },
      {
        author: {
          name: '이화가',
          nickname: 'leepainter',
          profileImage: 'https://picsum.photos/40/40?random=205',
          verified: true,
        },
        content: '자연의 아름다움이 잘 느껴져요!',
        createdAt: '2024-01-11T20:45:00Z',
        likes: 6,
        isLiked: true,
      },
      {
        author: {
          name: '박자연',
          nickname: 'parknature',
          profileImage: 'https://picsum.photos/40/40?random=204',
          verified: false,
        },
        content: '스케치 정말 예쁘네요!',
        createdAt: '2024-01-11T21:00:00Z',
        likes: 4,
        isLiked: false,
      },
    ],
  },
  {
    id: 3,
    author: {
      name: '파하모니카',
      nickname: 'paharmonica',
      profileImage: 'https://picsum.photos/40/40?random=3',
      verified: true,
    },
    content:
      '하모니카로 옛날 노래를 연주하고 있어요! 향수를 불러일으키는 멜로디예요 🎵 #하모니카 #옛날노래 #향수',
    images: [],
    category: 3,
    categoryName: '음악',
    createdAt: '2024-01-11T19:30:00Z',
    likes: 112,
    retweets: 32,
    comments: 0,
    isLiked: true,
    isRetweeted: false,
    hasMoreComments: false,
    commentList: [],
  },
  {
    id: 2,
    author: {
      name: '하배우',
      nickname: 'haactor',
      profileImage: 'https://picsum.photos/40/40?random=2',
      verified: false,
    },
    content:
      '연기 연습을 하고 있어요! 감정 표현이 정말 어렵지만 보람있어요 🎭 #연기 #감정표현 #연습',
    images: ['https://picsum.photos/500/300?random=46'],
    category: 4,
    categoryName: '영화',
    createdAt: '2024-01-11T18:45:00Z',
    likes: 178,
    retweets: 51,
    comments: 0,
    isLiked: false,
    isRetweeted: false,
    hasMoreComments: false,
    commentList: [],
  },
  {
    id: 1,
    author: {
      name: '갸과학',
      nickname: 'gyascience',
      profileImage: 'https://picsum.photos/40/40?random=1',
      verified: true,
    },
    content:
      '과학 도서를 읽으며 우주의 신비에 대해 배우고 있어요. 정말 경이로워요 🌌 #과학 #우주 #신비',
    images: [],
    category: 5,
    categoryName: '독서',
    createdAt: '2024-01-11T17:20:00Z',
    likes: 145,
    retweets: 42,
    comments: 18,
    isLiked: true,
    isRetweeted: true,
    hasMoreComments: true,
    commentList: [
      {
        author: {
          name: '박과학',
          nickname: 'parkscience',
          profileImage: 'https://picsum.photos/40/40?random=203',
          verified: false,
        },
        content: '어떤 과학 도서인가요? 저도 읽어보고 싶네요!',
        createdAt: '2024-01-11T17:35:00Z',
        likes: 11,
        isLiked: false,
      },
      {
        author: {
          name: '이우주',
          nickname: 'leespace',
          profileImage: 'https://picsum.photos/40/40?random=202',
          verified: true,
        },
        content: '우주의 신비는 정말 끝이 없죠!',
        createdAt: '2024-01-11T17:50:00Z',
        likes: 7,
        isLiked: true,
      },
      {
        author: {
          name: '김신비',
          nickname: 'kimmystery',
          profileImage: 'https://picsum.photos/40/40?random=201',
          verified: false,
        },
        content: '과학 도서 추천 감사합니다!',
        createdAt: '2024-01-11T18:05:00Z',
        likes: 5,
        isLiked: false,
      },
    ],
  },
];
